### PR TITLE
Removed AModel from models.py

### PR DESCRIPTION
**Pull request by djm**
Unless I'm missing something severe I can't see a reason for the `AModel` model included in models.py? It creates an unnecessary table when you run syncdb which, while not really an issue, is a small annoyance.

It isn't a requirement to have a model in the file so I have removed it and the tests still run fine (as they have their own models file); anyway, here's the commit if you wish to pull it.

Thanks for your work on this by the way, it's brilliant.

cheers, Darian

### CODE REVIEW

**Comment by gnotaras** [comment]
Is this project alive? Why do you still keep this model in this app?

**Comment by gnotaras** [comment]
Oops, just noticed that Amodel is only present in the version that is downloadable from pypi, but it has been corrected here on github. Please, upload a release without this unnecessary model on pypi. Thanks.

**Comment by djm** [comment]
This still exists on the "main" repo & branch of it and hasn't been merged yet, as far as I can tell - development seems dead.

**Comment by domguard** [comment]
I'm following flupke , as he has added very useful support for taggit custom "through" custom model

**Comment by djm** [comment]
Closing due to deadness.

**Pull request closed without merging**
